config/routes.rb
Todolist::Application.routes.draw do

  root :to => "kanbanlist#index"

  devise_for :users
  get 'tasks', :to => 'tasks#index', :as => :user_root

  get "kanbanlist/index"

  post "tasks/update_order"
  post "tasks/filter_or_update"
  post "tasks/silent_update"
  post "tasks/send_mail"
  get 'tasks/donelist'

  get "dashboard/index"
  resources :books
  resources :tasks
  resources :users

end

app/views/layouts/_book_list_dropdown_li.html.erb
              <li><a href="#" id="books_toggle_link" rel="tooltip" title="Toggle book list"><i class="icon-book"></i></a></li>

app/views/layouts/_delete_task_dialog.html.erb
<div class="modal hide fade" id="delete_task_in">
  <div class="modal-header">
    <h3>Delete task?</h3>
  </div>
  <div class="modal-body">
    <div id="delete_task_string"></div>
  </div>
  <div class="modal-footer">
    <button id="delete_task_ok_button" class="btn btn-primary">OK</button>
    <button id="delete_task_cancel_button" class="btn">Cancel</button>
  </div>
</div>

app/views/layouts/_layout_dropdown_li.html.erb
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Layout
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" id="layout_list">
                  <li><a href="#" onclick="selectLayout('landscape');">Landscape</a></li>
                  <li><a href="#" onclick="selectLayout('compact');">Compact</a></li>
                  <li><a href="#" onclick="selectLayout('compact2');">Compact2</a></li>
                  <li><a href="#" onclick="selectLayout('portrait');">Portrait</a></li>
                </ul>
              </li>

app/views/layouts/_new_book_dialog.html.erb
<div class="modal hide fade" id="book_in">
  <div class="modal-header">
    <h3>New Book</h3>
  </div>
  <div class="modal-body">
    <p>Please type new book name.</p>
    <form id="book_form">
      <input type="text" id="book_name" class="span2" placeholder="Book Name"/>
    </form>
  </div>
  <div class="modal-footer">
    <button id="new_book_button" class="btn btn-primary">New</button>
  </div>
</div>

app/views/layouts/_remove_book_dialog.html.erb
<div class="modal hide fade" id="remove_book_in">
  <div class="modal-header">
    <h3>Remove Current Book</h3>
  </div>
  <div class="modal-body">
    <p>Are you sure you want to remove current Book?</p>
    <p>All tasks of current book is removed.</p>
  </div>
  <div class="modal-footer">
    <button id="remove_book_button" class="btn btn-primary">OK</button>
    <button id="remove_book_cancel_button" class="btn">Cancel</button>
  </div>
</div>

app/views/layouts/_send_mail_dialog.html.erb
<div class="modal hide fade" id="mail_in">
  <div class="modal-header">
    <h3>Send the task list by Email</h3>
  </div>
  <div class="modal-body">
    <p>Please type email address(es).</p>
    <form id="mail_form">
      <input type="text" id="mail_addr" class="span4" placeholder="Mail Address" value="<%= @user_email %>"/>
      (separated by ",")
    </form>

    <p>Option: please type a comment to enter the body of email.</p>
    <form id="mail_comment_form">
      <input type="text" id="mail_comment" class="span5" placeholder="Comment" value=""/>
    </form>

    <div class="alert">
      Email will be sent from "<%= ENV['MAIL_ADDR'] %>".
    </div>

  </div>
  <div class="modal-footer">
    <button id="send_mail_button" class="btn btn-primary">Send</button>
  </div>
</div>

app/views/layouts/_set_bg_image_dialog.html.erb
<div class="modal hide fade" id="bg_image_in">
  <div class="modal-header">
    <h3>Set background image url</h3>
  </div>
  <div class="modal-body">
    <p>Please type background image url.</p>
    <form id="bg_image_form">
      <input type="text" id="image_url" class="span6" placeholder="Image URL" value=""/>
    <p>ex) http://hogehoge/fuga.jpg</p>
    </form>
  </div>
  <div class="modal-footer">
    <button id="set_bg_image_button" class="btn btn-primary">Set</button>
  </div>
</div>

app/views/layouts/_task_count_table.html.erb
<p>
<table id="task_count_table" >
  <tr>
    <td><div id="todo_h_num"  class="counts todo_h" >0</div></td>
    <td><div id="todo_m_num"  class="counts todo_m" >0</div></td>
    <td><div id="todo_l_num"  class="counts todo_l" >0</div></td>
    <td><div id="doing_num"   class="counts doing"  >0</div></td>
    <td><div id="waiting_num" class="counts waiting">0</div></td>
    <td><div id="done_num"    class="counts done"   >0</div></td>
  </tr>
</table>
</p>

app/views/layouts/_theme_dropdown_li.html.erb
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Theme 
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" id="theme_list">
                  <li><a href="#" onclick="selectTheme('default');">Default</a></li>
                  <li><a href="#" onclick="selectTheme('flat');">Flat</a></li>
                  <li><a href="#" onclick="selectTheme('snow');">Snow</a></li>
                </ul>
              </li>

app/views/layouts/_trial_feature_dropdown_li.html.erb
<li><a id="pomo_navi" href="#" rel="tooltip" title="Pomodoro Timer">
  <img class="icon-pomo" src="<%= image_path 'tomato.gif' %>" />
</a></li>
<li><%= link_to raw('<i class="icon-list"></i>'), tasks_donelist_path, { rel: "tooltip", title: "Go to DoneList" } %></li>
<li><a id="send_mail" href="#" rel="tooltip" title="Send list by mail"><i class="icon-envelope"></i></a></li>
<li><a id="set_bg_image" href="#" rel="tooltip" title="Set background image"><i class="icon-picture"></i></a></li>
<li class="dropdown" style="white-space: nowrap;">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" rel="tooltip" title="Auto loading">
    <i class="icon-refresh"></i>
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><a id="auto_loading" href="#"></a></li>
  </ul>
</li>
<% if !is_sample_user? %>
  <li><%= link_to raw('<i class="icon-user"></i>'), edit_user_path(current_user), { rel: "tooltip", title: "Edit user info" } %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="apple-mobile-web-app-capable" content="yes"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <title>かんばんりすと</title>
  <%= stylesheet_link_tag :application %>
  <%= stylesheet_link_tag "task_default" , id: "task_theme" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>

</head>
<body id="body_core" style="
 background-color: white;
 background-attachment: fixed;
 background-position: center top;
 background-repeat:  repeat;
 padding-top: 60px;
">
<% if ENV['GOOGLE_ANALYTICS_ID'] %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV['GOOGLE_ANALYTICS_ID'] %>', 'heroku.com');
  ga('send', 'pageview');
</script>
<% end %>

<header>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="brand" href="/">かんばんりすと</a>
        <div class="nav-collapse">
          <ul class="nav pull-left">
            <% if current_user %>
              <li><%= link_to raw('<i class="icon-eye-open"></i>'), dashboard_index_path, { rel: "tooltip", title: "Go to your dashboard" } %></li>
              <li><%= link_to raw('<i class="icon-home"></i>'), tasks_path, { rel: "tooltip", title: "Go to your kanbanlist" } %></li>
            <% end %>
            <% if params[:controller] == "tasks" and params[:action] == "index" %>
              <%= render "layouts/book_list_dropdown_li" %>
              <%= render "layouts/layout_dropdown_li" %>
              <%= render "layouts/theme_dropdown_li" %>
            <% end %>
          </ul>

          <% if params[:controller] == "tasks" and params[:action] == "index" %>
          <form id="filter_form" method="post" class="navbar-search pull-left">
            <input type="text" id="filter_str" class="search-query span2" value="" placeholder="Filter"/>
          </form>

          <div class="pull-left">
            <%= render "layouts/task_count_table" %>
          </div>
          <% end %>

          <ul class="nav pull-right">
            <% if params[:controller] == "tasks" and params[:action] == "index" %>
              <%= render "layouts/trial_feature_dropdown_li" %>
            <% end %>

            <% if current_user %>
              <li><%= link_to('Logout', [ :destroy, :user_session ], :class => '') %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</header>

<%= render "layouts/new_book_dialog" %>
<%= render "layouts/remove_book_dialog" %>
<%= render "layouts/send_mail_dialog" %>
<%= render "layouts/set_bg_image_dialog" %>
<%= render "layouts/delete_task_dialog" %>

<%= yield %>

  <footer>
    <span>
    © 2011 Naoki KODAMA. All rights reserved.
    </span>
  </footer>
</body>
</html>

app/views/layouts/application_smart_phone_iphone.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="apple-mobile-web-app-capable" content="yes"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <title>かんばんりすと</title>
  <%= stylesheet_link_tag    :application_smart_phone_iphone %>
  <script src="https://code.jquery.com/jquery-1.6.4.min.js"></script>
  <script src="https://code.jquery.com/ui/1.8.17/jquery-ui.min.js"></script>
  <%= javascript_include_tag :application_smart_phone_iphone %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>